[build]
  publish = "src/ui"
  command = "echo 'No build required for static site'"

[dev]
  framework = "#static"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "http://localhost:3000/health"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
